### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by jmank88** [gochain/rpc-proxy#37]
We should explore what is required to support WebSocket connections, because they allow for more features than HTTP.

**Comment by jmank88** [comment]
Maybe relevant: As of go 1.12, 
> The ReverseProxy now automatically proxies WebSocket requests.

https://tip.golang.org/doc/go1.12#net/http/httputil

**Comment by treeder** [comment]
We need to do this now for MEW: https://mobile.twitter.com/myetherwallet/status/1417410240220336131

@jmank88 could you try to get this working?
